### ISSUE TITLE
Question：Does “import-vm-disk-apb” need kubevirt StroageClass to create PVC after storage and kubevirt decoupled?

### ISSUE THREAD

**Issue by qwang1** [ansibleplaybookbundle/import-vm-disk-apb#4]
Hi @aglitke @rthallisey ,

So far kubevirt component and storage have been decoupled, provision kubevirt won't need/create storage，and users can choose storage they want. This APB is not updated for months, so I'd like to know if it still needs a StorageClass named "kubevirt" to provide storage interface to create PVC. Thanks.

**Comment by rthallisey** [comment]
This apb is replaced by https://github.com/ansibleplaybookbundle/import-vm-apb .   Refer to the import-vm-apb for updates.  Thanks @qwang1

**Comment by qwang1** [comment]
@rthallisey So the ServiceClass is kept there and shown on web console as well?

**Comment by rthallisey** [comment]
@qwang1 everything is in the import-vm-apb - name 'Import Virtual Machine' in the catalog UI.
